### ISSUE TITLE
Choose Paper Size

### ISSUE THREAD

**Issue by PetyaWebDesign** [Magik3a/DesignAndPrint#1]
I like the button, can you remove the actual paper size fields, and when the user clicks the button, they'll appear in modal.

**Comment by Magik3a** [comment]
I want the content for this row to be at least 35% on actual page size. That way i can make other rows with very large opacity but still visible, when you  continue with adding images, this row will animate (opacity: 0.2) and auto scroll down

**Comment by PetyaWebDesign** [comment]
Sounds good
