### ISSUE TITLE
Font

### ISSUE THREAD

**Issue by PetyaWebDesign** [Magik3a/DesignAndPrint#2]
https://www.google.com/fonts#QuickUsePlace:quickUse
Here is the font which I like

**Comment by Magik3a** [comment]
The link isn't open anything

**Comment by PetyaWebDesign** [comment]
Yep, I just notice that too. You can go to Google Fonts and choose "Lato" font.

**Comment by Magik3a** [comment]
I change the font but there is not much of a difference

**Comment by PetyaWebDesign** [comment]
There is a big difference :) much more better
