### ISSUE TITLE
Background

### ISSUE THREAD

**Issue by PetyaWebDesign** [Magik3a/DesignAndPrint#5]
I think if we use gray background on the page (excluding the menu because of the steps images) will be good. This way we'll separate visually the menu from the main content. I suggest #989898

**Comment by Magik3a** [comment]
Very good idea!!! We should consider maybe small image with repeat on the background, i think with no-scroll will be good to.

**Comment by PetyaWebDesign** [comment]
yep! can you apply that?

**Comment by Magik3a** [comment]
I need to find some image first
